version: '3.5'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - atk-network
    volumes:
      - .:/app
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - php
    restart: on-failure

  php:
    container_name: php
    build: .
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9003:9003"
      - "127.0.0.1:10137:10137"
      - "127.0.0.1:20080:20080"
    networks:
      - atk-network
    environment:
      - XDEBUG_TRIGGER=PHPSTORM
      - APP_ENV=dev
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
      - .:/app
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/config/ImageMagick-6/policy.xml:/etc/ImageMagick-6/policy.xml
    working_dir: /app
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql:8
    platform: linux/x86_64
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - atk-network
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/config/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atk
      MYSQL_ROOT_HOST: "%"
    restart: on-failure

networks:
  atk-network:
    driver: bridge

volumes:
  mysql-data: